version: '3.4'
services:
  autoheal:
    container_name: neo-local_autoheal
    depends_on:
      - neo-faucet
      - neo-nodes
      - neo-python
      - neo-scan-api
      - neo-scan-sync
      - notifications-server
      - postgres
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal
      - AUTOHEAL_INTERVAL=5
      - DOCKER_SOCK=/var/run/docker.sock
    image: willfarrell/autoheal
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

  neo-faucet:
    container_name: neo-faucet
    depends_on:
      - neo-scan-api
    environment:
      NEOSCAN: 'neo-scan-api:4000'
    image: 'cityofzion/neo-local-faucet:latest'
    links:
      - 'neo-scan-api:4000'
    ports:
      - '4002:4002'

  neo-nodes:
    container_name: neo-nodes
    image: 'cityofzion/neo-privatenet:2.7.6'
    ports:
      - '20333:20333'
      - '20334:20334'
      - '20335:20335'
      - '20336:20336'
      - '30333:30333'
      - '30334:30334'
      - '30335:30335'
      - '30336:30336'

  neo-python:
    container_name: neo-python
    depends_on:
      - neo-nodes
      - neo-scan-api
      - neo-scan-sync
    image: 'cityofzion/neo-python:v0.8.2'
    network_mode: host
    tty: true
    volumes:
      - './smart-contracts:/smart-contracts'
      - './wallets:/wallets'

  neo-scan-api:
    container_name: neo-scan-api
    depends_on:
      - postgres
      - neo-nodes
      - notifications-server
    environment:
      DB_DATABASE: neoscan_prodv
      DB_HOSTNAME: postgres
      DB_PASSWORD: postgres
      DB_USERNAME: postgres
      HOST: '${HOST_NAME}'
      NEO_NOTIFICATIONS_SERVER: 'http://${NOTIFICATIONS_SERVER}:8080/v1'
      NEO_SEEDS: >-
        http://${SEED_SERVER}:30333;http://${SEED_SERVER}:30334;http://${SEED_SERVER}:30335;http://${SEED_SERVER}:30336
      PORT: 4000
      REPLACE_OS_VARS: 'true'
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 20s
      test:
        - CMD
        - bash
        - '-c'
        - exec 6<>/dev/tcp/127.0.0.1/4000
      timeout: 10s
    image: 'registry.gitlab.com/cityofzion/neo-scan/api:latest'
    labels:
      autoheal: 'true'
    links:
      - 'neo-nodes:30333'
      - 'neo-nodes:30334'
      - 'neo-nodes:30335'
      - 'neo-nodes:30336'
    ports:
      - '4000:4000'
    restart: always

  neo-scan-sync:
    container_name: neo-scan-sync
    depends_on:
      - postgres
      - neo-nodes
      - notifications-server
    environment:
      DB_DATABASE: neoscan_prodv
      DB_HOSTNAME: postgres
      DB_PASSWORD: postgres
      DB_USERNAME: postgres
      NEO_NOTIFICATIONS_SERVER: 'http://${NOTIFICATIONS_SERVER}:8080/v1'
      NEO_SEEDS: >-
        http://${SEED_SERVER}:30333;http://${SEED_SERVER}:30334;http://${SEED_SERVER}:30335;http://${SEED_SERVER}:30336
      REPLACE_OS_VARS: 'true'
    image: 'registry.gitlab.com/cityofzion/neo-scan/sync:latest'
    links:
      - 'neo-nodes:30333'
      - 'neo-nodes:30334'
      - 'neo-nodes:30335'
      - 'neo-nodes:30336'

  notifications-server:
    command: >-
      /usr/bin/python3 /neo-python/neo/bin/api_server.py --config
      /neo-python/custom-config.json --port-rest 8080
    container_name: notifications-server
    depends_on:
      - neo-nodes
    image: 'cityofzion/neo-python:v0.8.2'
    ports:
      - '8080:8080'
    volumes:
      - './notifications-server.config.json:/neo-python/custom-config.json'

  postgres:
    container_name: postgres
    environment:
      POSTGRES_DB: neoscan_prodv
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    expose:
      - 5432
    image: 'postgres:10.5'
    